const TEAM_DATA = 
{
  "players": [
    {
      "id": "rec1rpIyF3P2Qwj0e",
      "firstName": "Andrea",
      "lastName": "Zaghet",
      "number": 45,
      "position": "",
      "goals": 9,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "02/08/2001",
      "birthPlace": "Pordenone",
      "address": "Via Noncello",
      "streetNumber": "23",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 339,
      "phone": "2149459",
      "fiscalCode": "ZGHNDR01M02G888E",
      "idCard": "CA95410MO",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "45",
      "jerseyTraining": ""
    },
    {
      "id": "rec2byQ6G99AmPuNp",
      "firstName": "Riccardo",
      "lastName": "Montagner",
      "number": 1,
      "position": "",
      "goals": 1,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "19/03/2001",
      "birthPlace": "Pordenone",
      "address": "Via Casut",
      "streetNumber": "147",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 320,
      "phone": "3846864 ",
      "fiscalCode": "MNTRCR01C19G888J",
      "idCard": "CA59580JQ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "2XL",
      "jerseyNumber": "1",
      "jerseyTraining": "SI"
    },
    {
      "id": "rec3vqVuZeACEBuG4",
      "firstName": "Nicholas",
      "lastName": "Moras",
      "number": 14,
      "position": "",
      "goals": 3,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "07/12/1996",
      "birthPlace": "Pordenone",
      "address": "Via Centrale",
      "streetNumber": "4",
      "city": "Porcia",
      "province": "PN",
      "postalCode": 33080,
      "phonePrefix": 342,
      "phone": "_0455412",
      "fiscalCode": "MRSNHL96T07G888Q",
      "idCard": "CA65192PJ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "14",
      "jerseyTraining": "SI"
    },
    {
      "id": "rec4DFFh69j5mVO5w",
      "firstName": "Raffaele",
      "lastName": "De Nuzzo",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "15/03/1984",
      "birthPlace": "Mesagne",
      "address": "Via Capitano Maso",
      "streetNumber": "7",
      "city": "Budoia",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "DNZRFL84C15F152L",
      "idCard": "AY2437298",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "rec4XZLyd5UyFODtJ",
      "firstName": "Manuel",
      "lastName": "Michelin",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "19/10/1980",
      "birthPlace": "Sacile",
      "address": "Piazza della Vittoria",
      "streetNumber": "123",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 347,
      "phone": "6764217",
      "fiscalCode": "MCHMNL80R19H657R",
      "idCard": "CA78403QK",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "rec72aqwXtlPTiny1",
      "firstName": "Francesco Saverio ",
      "lastName": "Furia",
      "number": 7,
      "position": "",
      "goals": 2,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "14/01/1997",
      "birthPlace": "Cinquefrondi",
      "address": "Via Montagna",
      "streetNumber": "31",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 339,
      "phone": "2803825",
      "fiscalCode": "FRUFNC97A14C710D",
      "idCard": "AY5942328",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "7",
      "jerseyTraining": "SI"
    },
    {
      "id": "rec7iCUdx08osmZro",
      "firstName": "Daniele",
      "lastName": "Carlet",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "06/12/1983",
      "birthPlace": "Sacile",
      "address": "Strada delle Roncadelle",
      "streetNumber": "2",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "CRLDNL83T06H657Z",
      "idCard": "CA78944JH",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "rec8RtRKH93DQcIIr",
      "firstName": "Mauro",
      "lastName": "Giust",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "11/06/1986",
      "birthPlace": "Pordenone",
      "address": "Via Trieste",
      "streetNumber": "10",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "GSTMRA86H11G888G",
      "idCard": "CA71444DC",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "rec8SGRB76YfdlkLt",
      "firstName": "Behar",
      "lastName": "Dervishi",
      "number": 2,
      "position": "",
      "goals": 7,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "06/05/1994",
      "birthPlace": "Kosovo",
      "address": "Via Margherita Giol",
      "streetNumber": "7",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 386,
      "phone": "49767909",
      "fiscalCode": "",
      "idCard": "",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "2",
      "jerseyTraining": "SI"
    },
    {
      "id": "recB5LQB9exqpakZc",
      "firstName": "Matteo",
      "lastName": "Astolfi",
      "number": 10,
      "position": "",
      "goals": 3,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "28/07/1996",
      "birthPlace": "Pordenone",
      "address": "Campo Marzio",
      "streetNumber": "6",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 331,
      "phone": "7848861",
      "fiscalCode": "STLMTT96L28G888C",
      "idCard": "AV4607945",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "S",
      "jerseyNumber": "10",
      "jerseyTraining": "SI"
    },
    {
      "id": "recCOWy6GQlIvRXGR",
      "firstName": "Lorenzo",
      "lastName": "Muraj",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "05/07/2002",
      "birthPlace": "Montevarchi",
      "address": "Via Giuseppe Garibaldi",
      "streetNumber": "14",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "MRJLNZ02L05F656Q",
      "idCard": "CA43088MJ",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recDWTBiz2T63HYwF",
      "firstName": "Antonio Frangella",
      "lastName": "Martin",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "26/04/1984",
      "birthPlace": "Pordenone",
      "address": "Vicolo Scudet",
      "streetNumber": "2",
      "city": "Polcenigo",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "FRNMTN84D26Z600V",
      "idCard": "CA74219MI",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recDnlqCISrVMdX3x",
      "firstName": "Mateo",
      "lastName": "Sheshi",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "30/09/2001",
      "birthPlace": "Pordenone",
      "address": "Via Ronche",
      "streetNumber": "8",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 346,
      "phone": "8458396",
      "fiscalCode": "SHSMTA01P30G888O",
      "idCard": "CA63411FF",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recFH3er7LQMWm0HQ",
      "firstName": "Andreea Alexandra",
      "lastName": "Lefter",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "F",
      "birthDate": "20/01/1997",
      "birthPlace": "Romania",
      "address": "Via 4 Novembre",
      "streetNumber": "57",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 333,
      "phone": "1502953",
      "fiscalCode": "LFTNRL97A60Z129J",
      "idCard": "AV9559701",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recG1RhGqjvCtD4Zu",
      "firstName": "Giovanni",
      "lastName": "Brugnone",
      "number": 17,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "27/08/1992",
      "birthPlace": "Napoli",
      "address": "Strada Casut",
      "streetNumber": "14",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 334,
      "phone": "1848851",
      "fiscalCode": "BRGGNN92M27F839X",
      "idCard": "CA29294CA",
      "kit": "SI",
      "bag": "SI",
      "jacket": "",
      "size": "M",
      "jerseyNumber": "17",
      "jerseyTraining": ""
    },
    {
      "id": "recHwPGWy9yHpNeys",
      "firstName": "Davide",
      "lastName": "Viol ",
      "number": 27,
      "position": "",
      "goals": 2,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "22/01/2005",
      "birthPlace": "Pordenone",
      "address": "Via Pasubio",
      "streetNumber": "10",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 370,
      "phone": "3061069",
      "fiscalCode": "VLIDVD05A22G888S",
      "idCard": "CA08925LN",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "27",
      "jerseyTraining": "SI"
    },
    {
      "id": "recJU4u5OW1bHxg0r",
      "firstName": "Romario",
      "lastName": "Jakupi",
      "number": 9,
      "position": "",
      "goals": 2,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "14/08/1995",
      "birthPlace": "Albania",
      "address": "Via Liguria",
      "streetNumber": "68",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 348,
      "phone": "9605075",
      "fiscalCode": "JKPRMR95M14Z100K",
      "idCard": "CA29110MZ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "9",
      "jerseyTraining": "SI"
    },
    {
      "id": "recLE0dySh7GkE8vc",
      "firstName": "Arber",
      "lastName": "Gorenca",
      "number": 1,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "28/09/1998",
      "birthPlace": "Vittorio Veneto",
      "address": "Via C. Battisti",
      "streetNumber": "42",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 371,
      "phone": "3261805",
      "fiscalCode": "GRNRBR98P28M089Z",
      "idCard": "CA27372KW",
      "kit": "SI",
      "bag": "",
      "jacket": "",
      "size": "M",
      "jerseyNumber": "1",
      "jerseyTraining": ""
    },
    {
      "id": "recLjnE4TixUrmAzC",
      "firstName": "Noah Gabriel",
      "lastName": "Zandonà",
      "number": 69,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "30/05/1998",
      "birthPlace": "Vittorio Veneto",
      "address": "Via V. Fasan",
      "streetNumber": "53",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 366,
      "phone": "3543440",
      "fiscalCode": "ZNDNGB98E30M089A",
      "idCard": "AV9547062",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "69",
      "jerseyTraining": "SI"
    },
    {
      "id": "recLjqX6GwPCOiZXM",
      "firstName": "Simone",
      "lastName": "De Marco",
      "number": 21,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "04/09/2000",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Canevon",
      "streetNumber": "19",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 333,
      "phone": "6833498",
      "fiscalCode": "DMRSMN00P04M089B",
      "idCard": "CA81573GJ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "21",
      "jerseyTraining": ""
    },
    {
      "id": "recMkr6vXGz9ZQ56C",
      "firstName": "Davide",
      "lastName": "Morellato",
      "number": 12,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "14/12/1987",
      "birthPlace": "Maniago",
      "address": "Via Garibaldi",
      "streetNumber": "6",
      "city": "Aviano",
      "province": "PN",
      "postalCode": 33081,
      "phonePrefix": 346,
      "phone": "6117653",
      "fiscalCode": "MRLDVD87T14E889B",
      "idCard": "CA19261FZ",
      "kit": "SI",
      "bag": "",
      "jacket": "",
      "size": "XXL",
      "jerseyNumber": "12",
      "jerseyTraining": "SI"
    },
    {
      "id": "recNmbeA2lbaghPP9",
      "firstName": "Brantil",
      "lastName": "Cupa",
      "number": 10,
      "position": "",
      "goals": 11,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "15/04/1991",
      "birthPlace": "Albania",
      "address": "Via Giuseppe Mazzini",
      "streetNumber": "18",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 342,
      "phone": "1452209",
      "fiscalCode": "CPUBNT91D15Z100P",
      "idCard": "CA45289JF",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "10",
      "jerseyTraining": "SI"
    },
    {
      "id": "recQAgdtbcaUfYLWo",
      "firstName": "Davide",
      "lastName": "Sandrin",
      "number": 71,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "20/09/1999",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Roncat",
      "streetNumber": "22",
      "city": "Gaiarine",
      "province": "TV",
      "postalCode": 31018,
      "phonePrefix": 340,
      "phone": "4813406",
      "fiscalCode": "SNDDVD99P20M089W",
      "idCard": "CA34467NE",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "71",
      "jerseyTraining": "SI"
    },
    {
      "id": "recQGRV3RUOm0UXbY",
      "firstName": "Nicola",
      "lastName": "Rosolen",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "18/12/1997",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Ippolito Nievo,",
      "streetNumber": "8",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 346,
      "phone": "9704458",
      "fiscalCode": "RSLNCL97T18M089H",
      "idCard": "AV9569824",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recUH9ulSbQ7QW0ga",
      "firstName": "Alex",
      "lastName": "De Zan",
      "number": 19,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "12/02/2001",
      "birthPlace": "Pordenone",
      "address": "Via Arrigo Boito",
      "streetNumber": "2",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 333,
      "phone": "9815663",
      "fiscalCode": "DZNLXA01B12G888S",
      "idCard": "CA32587RB",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "19",
      "jerseyTraining": "SI"
    },
    {
      "id": "recUPDB3zyglfUpip",
      "firstName": "Marco",
      "lastName": "Lombino",
      "number": 10,
      "position": "",
      "goals": 1,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "10/05/1984",
      "birthPlace": "Palermo",
      "address": "Borgo Schiavoi",
      "streetNumber": "27E",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 392,
      "phone": "1061131",
      "fiscalCode": "LMBMRC84E10G273T",
      "idCard": "CA386GK",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "10",
      "jerseyTraining": "SI"
    },
    {
      "id": "recVBOI7MCS1Mnd76",
      "firstName": "Matteo",
      "lastName": "Lot",
      "number": 29,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "12/01/1999",
      "birthPlace": "San Vito al Tagliamento",
      "address": "Via Calderozze",
      "streetNumber": "27",
      "city": "Gaiarine",
      "province": "TV",
      "postalCode": 31018,
      "phonePrefix": 334,
      "phone": "9967232",
      "fiscalCode": "LTOMTT99A12I403K",
      "idCard": "CA73374DU",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "29",
      "jerseyTraining": "SI"
    },
    {
      "id": "recXEmufw25jSea4c",
      "firstName": "Andrea",
      "lastName": "Breda",
      "number": 11,
      "position": "",
      "goals": 4,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "07/04/1996",
      "birthPlace": "Conegliano",
      "address": "Via G. Mameli",
      "streetNumber": "31",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 347,
      "phone": "6084907",
      "fiscalCode": "BRDNDR96D07C957B",
      "idCard": "AY0265723",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "XL",
      "jerseyNumber": "11",
      "jerseyTraining": ""
    },
    {
      "id": "recXhHyZr0yd5KZCx",
      "firstName": "Andrea",
      "lastName": "Tavian",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "26/02/1985",
      "birthPlace": "Sacile",
      "address": "Strada Vic. Piai della Vigna",
      "streetNumber": "5",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "TVNNDR85B26H657V",
      "idCard": "CA66575JO",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recYhzOsFEjS7YRa4",
      "firstName": "Ivan",
      "lastName": "Carlet",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "24/05/1988",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Ernesto Balbinot",
      "streetNumber": "13",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "CRLVNI88E24M089I",
      "idCard": "CA08767HI",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "reca1jjvIhiL7eoD7",
      "firstName": "Andrea",
      "lastName": "Nadal",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "26/03/1993",
      "birthPlace": "Pordenone",
      "address": "Via Nasse",
      "streetNumber": "3",
      "city": "Orsago",
      "province": "TV",
      "postalCode": 31010,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "NDLNDR93C26G888G",
      "idCard": "CA08412RY",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "reccnLX2H7KZwdzDR",
      "firstName": "Mosè",
      "lastName": "Viol ",
      "number": 5,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "21/05/1998",
      "birthPlace": "Pordenone",
      "address": "Via Pasubio",
      "streetNumber": "10",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 366,
      "phone": "4448120",
      "fiscalCode": "VLIMSO98E21G888O",
      "idCard": "CA24184MM",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "5",
      "jerseyTraining": "SI"
    },
    {
      "id": "recdookEHLf71ZYMc",
      "firstName": "Federico",
      "lastName": "Di Lollo",
      "number": 8,
      "position": "",
      "goals": 2,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "18/09/1998",
      "birthPlace": "Pordenone",
      "address": "Via Maestri del lavoro",
      "streetNumber": "4",
      "city": "Cordenons",
      "province": "PN",
      "postalCode": 33084,
      "phonePrefix": 349,
      "phone": "7801468",
      "fiscalCode": "DLLFRC98P18G888L",
      "idCard": "AY5031192",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "8",
      "jerseyTraining": "SI"
    },
    {
      "id": "recf6DBwRRuuw36FV",
      "firstName": "Luca",
      "lastName": "Stefanizzi",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "22/06/1989",
      "birthPlace": "San Pietro Vernotico",
      "address": "Via Vittorio Veneto",
      "streetNumber": "41",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "STFLCU89H22I119G",
      "idCard": "CA40859HO",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recfwGgn90RazSnnb",
      "firstName": "Diego",
      "lastName": "Modolo ",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "05/08/2001",
      "birthPlace": "Pordenone",
      "address": "Via Leonardo Da Vinci",
      "streetNumber": "22",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 366,
      "phone": "8199258",
      "fiscalCode": "MDLDGI01M05G888G",
      "idCard": "CA80890ET",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recgI7ErafdFEpbqT",
      "firstName": "Johann",
      "lastName": "De Martin",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "11/08/1981",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Ippolito Nievo",
      "streetNumber": "54",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "DMRJNN81M11M089U",
      "idCard": "AV9569723",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "rechqTGpBcBQlmR7O",
      "firstName": "Klevis",
      "lastName": "Cupa",
      "number": 11,
      "position": "",
      "goals": 4,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "09/08/1996",
      "birthPlace": "Albania",
      "address": "Via Giuseppe Mazzini",
      "streetNumber": "18",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 346,
      "phone": "8462678",
      "fiscalCode": "CPUKVS96M09Z100K",
      "idCard": "CA82191JB",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "11",
      "jerseyTraining": "SI"
    },
    {
      "id": "recipQkJ8ihU67WYg",
      "firstName": "Nicholas",
      "lastName": "De Martin",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "16/07/1982",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Borgo Martin",
      "streetNumber": "48",
      "city": "Sarmede",
      "province": "TV",
      "postalCode": 31026,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "DMRNLS82L16M089P",
      "idCard": "AY5942256",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "reckPfRXt34POoO9L",
      "firstName": "Elia",
      "lastName": "Viol ",
      "number": 22,
      "position": "",
      "goals": 5,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "25/07/2000",
      "birthPlace": "Pordenone",
      "address": "Via Pasubio",
      "streetNumber": "10",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 329,
      "phone": "2934749",
      "fiscalCode": "VLILEI00L25G888K",
      "idCard": "CA8985MJ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "22",
      "jerseyTraining": "SI"
    },
    {
      "id": "reckRtTUTXW6pvfJ9",
      "firstName": "Davide",
      "lastName": "Manfè",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "22/04/1991",
      "birthPlace": "Pordenone",
      "address": "Via Trento",
      "streetNumber": "31",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "MNFDVD91D22G888S",
      "idCard": "CA92059RZ",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "reckWEgVwuKSG9HRe",
      "firstName": "Luciano",
      "lastName": "Zandonà",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "03/07/1990",
      "birthPlace": "Sacile",
      "address": "Via Col di Lana",
      "streetNumber": "55",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": "",
      "phone": "",
      "fiscalCode": "ZNDLCN90L03H657S",
      "idCard": "TV5626081J",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "reckcb1e1J6LW6Pdc",
      "firstName": "Ymer",
      "lastName": "Hasanbelli",
      "number": 18,
      "position": "",
      "goals": 4,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "25/06/1991",
      "birthPlace": "Albania",
      "address": "Via Antonio Gramsci",
      "streetNumber": "10",
      "city": "Sacile",
      "province": "PN",
      "postalCode": 33077,
      "phonePrefix": 345,
      "phone": "9205972",
      "fiscalCode": "HSNYMR91H25Z100M",
      "idCard": "AY0266369",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "18",
      "jerseyTraining": ""
    },
    {
      "id": "reclQ5oWXgWcvmgmL",
      "firstName": "Manuele",
      "lastName": "Santarossa",
      "number": 24,
      "position": "",
      "goals": 2,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "03/07/1999",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Doge A.IV Mocenigo",
      "streetNumber": "10",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": 345,
      "phone": "8744425",
      "fiscalCode": "SNTMNL99L03M089J",
      "idCard": "CA97192FH",
      "kit": "SI",
      "bag": "SI",
      "jacket": "",
      "size": "L",
      "jerseyNumber": "24",
      "jerseyTraining": "SI"
    },
    {
      "id": "recmG5btZS47M49zg",
      "firstName": "Manuel Claudio",
      "lastName": "Querinuzzi",
      "number": 17,
      "position": "",
      "goals": 5,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "24/11/2001",
      "birthPlace": "Pordenone",
      "address": "Via S. Eurosia ",
      "streetNumber": "9",
      "city": "San Quirino",
      "province": "PN",
      "postalCode": 33080,
      "phonePrefix": 331,
      "phone": "1247825",
      "fiscalCode": "QRNMLC01S24G888I",
      "idCard": "CA61406HQ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "S",
      "jerseyNumber": "17",
      "jerseyTraining": "SI"
    },
    {
      "id": "recpCx9W3fLxYfFIb",
      "firstName": "Lorenzo",
      "lastName": "Roman",
      "number": 4,
      "position": "",
      "goals": 3,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "05/10/2000",
      "birthPlace": "Pordenone",
      "address": "Viale M. Grigoletti",
      "streetNumber": "80",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 377,
      "phone": "4782051",
      "fiscalCode": "RMNLNZ00R05G888O",
      "idCard": "AY2447616",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "4",
      "jerseyTraining": "SI"
    },
    {
      "id": "recqnSifca2Lu7jRa",
      "firstName": "Egli",
      "lastName": "Cupa",
      "number": 0,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "16/10/2000",
      "birthPlace": "Pordenone",
      "address": "Via San Giacomo",
      "streetNumber": "12",
      "city": "Brugnera",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 329,
      "phone": "3217672",
      "fiscalCode": "GPUGLE00R16G888X",
      "idCard": "CA99143GB",
      "kit": "",
      "bag": "",
      "jacket": "",
      "size": "",
      "jerseyNumber": "",
      "jerseyTraining": ""
    },
    {
      "id": "recs9GBgsUNyEBOjn",
      "firstName": "Andrea",
      "lastName": "Tarozzo",
      "number": 4,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "05/12/1991",
      "birthPlace": "Rovigo",
      "address": "Via 25 Aprile",
      "streetNumber": "44",
      "city": "Villadose",
      "province": "RO",
      "postalCode": 45010,
      "phonePrefix": 329,
      "phone": "7897967",
      "fiscalCode": "TRZNDR91T05H620J",
      "idCard": "CA00106GG",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "4",
      "jerseyTraining": ""
    },
    {
      "id": "recv2Lyc1Wk0DEumW",
      "firstName": "Tommaso",
      "lastName": "Feltrin",
      "number": 15,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "19/02/1999",
      "birthPlace": "Pordenone",
      "address": "Strada Cal di Mezzo",
      "streetNumber": "15",
      "city": "Gaiarine",
      "province": "TV",
      "postalCode": 31018,
      "phonePrefix": 346,
      "phone": "4346336",
      "fiscalCode": "FLTTMS99B19G888P",
      "idCard": "CA55740DJ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "S",
      "jerseyNumber": "15",
      "jerseyTraining": "SI"
    },
    {
      "id": "recvUJPXHiSTcE0Ea",
      "firstName": "Kevin",
      "lastName": "Bessega",
      "number": 58,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "14/08/2001",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Strada Maestra D'Italia",
      "streetNumber": "28",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": 345,
      "phone": "2355487",
      "fiscalCode": "BSSKVN01M14M089F",
      "idCard": "CA03129FC",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "XL",
      "jerseyNumber": "58",
      "jerseyTraining": ""
    },
    {
      "id": "recx3LzNKL7YJXJun",
      "firstName": "Daniele",
      "lastName": "Toffoli",
      "number": 6,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "11/03/1996",
      "birthPlace": "Pordenone",
      "address": "Via Montello",
      "streetNumber": "29",
      "city": "Caneva",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 349,
      "phone": "2262672",
      "fiscalCode": "TFFDNL96C11G888V",
      "idCard": "CA77062EL",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "XL",
      "jerseyNumber": "6",
      "jerseyTraining": "SI"
    },
    {
      "id": "recxUtvO909Ilhftm",
      "firstName": "Denis",
      "lastName": "Antonutti",
      "number": 99,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "21/09/2001",
      "birthPlace": "Pordenone",
      "address": "Via Crosetta",
      "streetNumber": "32",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 331,
      "phone": "8806168",
      "fiscalCode": "NTNDNS01P21G888D",
      "idCard": "CA37455JY",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "99",
      "jerseyTraining": "SI"
    },
    {
      "id": "recxcMZkwojRT9pGk",
      "firstName": "Nicola",
      "lastName": "Malnis",
      "number": 9,
      "position": "",
      "goals": 0,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "15/02/2002",
      "birthPlace": "Motta di Livenza",
      "address": "Via Oberdan",
      "streetNumber": "7",
      "city": "Fontanafredda",
      "province": "PN",
      "postalCode": 33074,
      "phonePrefix": 329,
      "phone": "7652519",
      "fiscalCode": "MLNNCL02B15F770V",
      "idCard": "CA30765RJ",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "L",
      "jerseyNumber": "9",
      "jerseyTraining": "SI"
    },
    {
      "id": "recxlbCzejuWkUw7I",
      "firstName": "Giuliano",
      "lastName": "Cupa",
      "number": 7,
      "position": "",
      "goals": 3,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "09/09/2000",
      "birthPlace": "Vittorio Veneto",
      "address": "Via Camol",
      "streetNumber": "1",
      "city": "Brugnera",
      "province": "PN",
      "postalCode": 33070,
      "phonePrefix": 320,
      "phone": "2689188",
      "fiscalCode": "CPUGLN00P09M089W",
      "idCard": "CA75053CE",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "7",
      "jerseyTraining": ""
    },
    {
      "id": "reczYHG8kWsSsSzgA",
      "firstName": "Matteo",
      "lastName": "Carlet",
      "number": 8,
      "position": "",
      "goals": 2,
      "assists": 0,
      "motm": 0,
      "gender": "M",
      "birthDate": "04/04/1995",
      "birthPlace": "Vittorio Veneto",
      "address": "Via General Cantore",
      "streetNumber": "4",
      "city": "Cordignano",
      "province": "TV",
      "postalCode": 31016,
      "phonePrefix": 347,
      "phone": "8079025",
      "fiscalCode": "CRLMTT95D04M089Z",
      "idCard": "AZ1438569",
      "kit": "SI",
      "bag": "SI",
      "jacket": "SI",
      "size": "M",
      "jerseyNumber": "8",
      "jerseyTraining": "SI"
    }
  ],
  "matches": [
    {
      "id": "rec1tn8pZZrsClnXM",
      "type": "match",
      "title": "TC Caneva vs S. MICHELE FAGNIGOLA",
      "date": "2025-12-15",
      "time": "20:45",
      "location": "FAGNIGOLA",
      "opponent": "S. MICHELE FAGNIGOLA",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec29XncaDZ1il2LP",
      "type": "match",
      "title": "TC Caneva vs ASTRA SAN VITO",
      "date": "2025-11-06",
      "time": "21:15",
      "location": "PALA ASTRA",
      "opponent": "ASTRA SAN VITO",
      "result": "7-6",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec2lcgeWoEIjYIC6",
      "type": "match",
      "title": "TC Caneva vs ROLLER SDM",
      "date": "2025-12-04",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "ROLLER SDM",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rec3F8UazHsXAJcTt",
      "type": "match",
      "title": "TC Caneva vs BOCA SENIOR",
      "date": "2025-10-30",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "BOCA SENIOR",
      "result": "1-3",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rec3LkVMF4FmZ0uYA",
      "type": "match",
      "title": "TC Caneva vs LIVENZA FUTSAL",
      "date": "2026-01-22",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "LIVENZA FUTSAL",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rec3im6xNe7j9CrZP",
      "type": "match",
      "title": "TC Caneva vs SACILE CALCIO A 5",
      "date": "2025-11-06",
      "time": "21:30",
      "location": "SACILE",
      "opponent": "SACILE CALCIO A 5",
      "result": "4-3",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec3zj3tSnO0IzOqF",
      "type": "match",
      "title": "TC Caneva vs BOMBA C5",
      "date": "2025-10-24",
      "time": "20:30",
      "location": "VALERY SPACE",
      "opponent": "BOMBA C5",
      "result": "2-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec4oEgIcH3vivdga",
      "type": "match",
      "title": "TC Caneva vs LIBERTAS C5",
      "date": "2025-12-04",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "LIBERTAS C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recAL7oAGLqyvgyx4",
      "type": "match",
      "title": "TC Caneva vs FCS",
      "date": "2025-10-30",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "FCS",
      "result": "4-7",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recBmIO9wCikSA01D",
      "type": "match",
      "title": "TC Caneva vs ATLETICO CONEGLIANO C5",
      "date": "2025-11-18",
      "time": "21:30",
      "location": "CONEGLIANO",
      "opponent": "ATLETICO CONEGLIANO C5",
      "result": "3-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recDAzLnpPRLzPnKl",
      "type": "match",
      "title": "TC Caneva vs BOWMAN PUB C5",
      "date": "2025-12-12",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "BOWMAN PUB C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recDMiOZV98zKfKaT",
      "type": "match",
      "title": "TC Caneva vs BCC PORDENONESE E MONSILE",
      "date": "2026-01-23",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "BCC PORDENONESE E MONSILE",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recEMUk5PaeoIQzC6",
      "type": "match",
      "title": "TC Caneva vs PIZZERIA AMICI MIEI C5",
      "date": "2025-10-16",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "PIZZERIA AMICI MIEI C5",
      "result": "1-3",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recEaGnxMoz0hbM4Z",
      "type": "match",
      "title": "TC Caneva vs PIZZERIA DA MARIO",
      "date": "2025-11-03",
      "time": "20:30",
      "location": "FANNA",
      "opponent": "PIZZERIA DA MARIO",
      "result": "9-1",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recFikcX4135keURD",
      "type": "match",
      "title": "TC Caneva vs BLACKMAGIC",
      "date": "2026-01-22",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "BLACKMAGIC",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recHK7tbomPmaVVyG",
      "type": "match",
      "title": "TC Caneva vs ATLETICO MARENO C5",
      "date": "2025-11-14",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "ATLETICO MARENO C5",
      "result": "5-1",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recQNnsIvhcZTojfa",
      "type": "match",
      "title": "TC Caneva vs PIGOZZI TEAM",
      "date": "2025-10-16",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "PIGOZZI TEAM",
      "result": "5-5",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recQzHSlVra1JU4yP",
      "type": "match",
      "title": "TC Caneva vs FUTSAL OLME' 2012",
      "date": "2025-11-20",
      "time": "20:30",
      "location": "CESSALTO",
      "opponent": "FUTSAL OLME' 2012",
      "result": "4-9",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recUZvKUVy4DmTI3Y",
      "type": "match",
      "title": "TC Caneva vs A.S.D. ORIGINALS 2022",
      "date": "2025-10-24",
      "time": "21:30",
      "location": "S.PIETRO DI FELETTO",
      "opponent": "A.S.D. ORIGINALS 2022",
      "result": "3-3",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recV1a6vmvQwPjh4M",
      "type": "match",
      "title": "TC Caneva vs CAVOLANO UNITED",
      "date": "2025-11-13",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "CAVOLANO UNITED",
      "result": "1-3",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recW731hixsbngLyb",
      "type": "match",
      "title": "TC Caneva vs SCAFATI FUTSAL",
      "date": "2025-11-24",
      "time": "21:30",
      "location": "CORDENONS",
      "opponent": "SCAFATI FUTSAL",
      "result": "9-2",
      "homeAway": "",
      "round": ""
    },
    {
      "id": "recXNhEW5zHMDFdXE",
      "type": "match",
      "title": "TC Caneva vs SAN GIORGIO",
      "date": "2025-10-20",
      "time": "20:30",
      "location": "VALERY SPACE",
      "opponent": "SAN GIORGIO",
      "result": "3-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recYvei6zTqkUjonx",
      "type": "match",
      "title": "TC Caneva vs FUTSAL OLME' 2012",
      "date": "2025-11-27",
      "time": "20:30",
      "location": "CESSALTO",
      "opponent": "FUTSAL OLME' 2012",
      "result": "4-8",
      "homeAway": "trasferta",
      "round": ""
    },
    {
      "id": "recg5pAiv7sRSEXrv",
      "type": "match",
      "title": "TC Caneva vs CALCIO A 5 ANZANO",
      "date": "2025-11-28",
      "time": "20:30",
      "location": "FREGONA (TV)",
      "opponent": "CALCIO A 5 ANZANO",
      "result": "2-5",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rechUan3g8uBwLaL2",
      "type": "match",
      "title": "TC Caneva vs FC REAL CELTIC",
      "date": "2026-01-09",
      "time": "20:10",
      "location": "ZOPPOLA",
      "opponent": "FC REAL CELTIC",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recifWHt5FmmKWgg8",
      "type": "match",
      "title": "TC Caneva vs CAFFE' CARIOCA",
      "date": "2025-12-15",
      "time": "20:45",
      "location": "PASIANO",
      "opponent": "CAFFE' CARIOCA",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recjfk8IygZGq7TcH",
      "type": "match",
      "title": "TC Caneva vs PORDENONE NAONIS FUTSAL",
      "date": "2025-10-17",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "PORDENONE NAONIS FUTSAL",
      "result": "6-1",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recmmoOg2QmXQXlve",
      "type": "match",
      "title": "TC Caneva vs NORMANNI",
      "date": "2025-11-13",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "NORMANNI",
      "result": "1-5",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "reco0LuLWHzlV2t3j",
      "type": "match",
      "title": "TC Caneva vs GREENFUTSAL",
      "date": "2025-12-11",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "GREENFUTSAL",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recoKVFtdCi0xJTGO",
      "type": "match",
      "title": "TC Caneva vs ASD ICEM C5",
      "date": "2025-11-28",
      "time": "20:15",
      "location": "VALERY SPACE",
      "opponent": "ASD ICEM C5",
      "result": "6-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recrUR9kIAOq6pl5N",
      "type": "match",
      "title": "TC Caneva vs ASD ICEM C5",
      "date": "2025-12-05",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "ASD ICEM C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recsEEZLpPzDAzrel",
      "type": "match",
      "title": "TC Caneva vs FASAN MOTORS C5",
      "date": "2025-12-11",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "FASAN MOTORS C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rectACT7lXDleEGL5",
      "type": "match",
      "title": "TC Caneva vs I FANTAS",
      "date": "2025-10-31",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "I FANTAS",
      "result": "4-4",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recw6MXBm1KG1CFXo",
      "type": "match",
      "title": "TC Caneva vs STELLA D'ARGENTO",
      "date": "2025-12-15",
      "time": "22:00",
      "location": "PASIANO",
      "opponent": "STELLA D'ARGENTO",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recwVkNFEN8JyQhBQ",
      "type": "match",
      "title": "TC Caneva vs PONTE 94",
      "date": "2025-11-17",
      "time": "21:15",
      "location": "FIASCHETTI",
      "opponent": "PONTE 94",
      "result": "1-7",
      "homeAway": "casa",
      "round": ""
    },
    {
      "id": "recxvu5EEXgqAsFDG",
      "type": "match",
      "title": "TC Caneva vs CENTRO EDIL LEGNO",
      "date": "2025-11-28",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "CENTRO EDIL LEGNO",
      "result": "7-2",
      "homeAway": "trasferta",
      "round": "andata"
    }
  ],
  "trainings": [
    {
      "id": "rec3ocuazTMO1Ndx3",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec4GUj2OZsgFZRb1",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec5mDhvUpUtpnKDy",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec5uAjK1Ds6p1wA3",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec7b7Xx5h0BqvLgp",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec9lSTh5sHGMApjU",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "recNQDKG7cbtXjzKN",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "recXREj36QwTNvz7y",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "reccUOX2btwLUxTaf",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rech9lmvj9m7ggbbK",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rechG4sFM0NarecXh",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    }
  ],
  "events": [
    {
      "id": "rec1tn8pZZrsClnXM",
      "type": "match",
      "title": "TC Caneva vs S. MICHELE FAGNIGOLA",
      "date": "2025-12-15",
      "time": "20:45",
      "location": "FAGNIGOLA",
      "opponent": "S. MICHELE FAGNIGOLA",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec29XncaDZ1il2LP",
      "type": "match",
      "title": "TC Caneva vs ASTRA SAN VITO",
      "date": "2025-11-06",
      "time": "21:15",
      "location": "PALA ASTRA",
      "opponent": "ASTRA SAN VITO",
      "result": "7-6",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec2lcgeWoEIjYIC6",
      "type": "match",
      "title": "TC Caneva vs ROLLER SDM",
      "date": "2025-12-04",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "ROLLER SDM",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rec3F8UazHsXAJcTt",
      "type": "match",
      "title": "TC Caneva vs BOCA SENIOR",
      "date": "2025-10-30",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "BOCA SENIOR",
      "result": "1-3",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rec3LkVMF4FmZ0uYA",
      "type": "match",
      "title": "TC Caneva vs LIVENZA FUTSAL",
      "date": "2026-01-22",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "LIVENZA FUTSAL",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rec3im6xNe7j9CrZP",
      "type": "match",
      "title": "TC Caneva vs SACILE CALCIO A 5",
      "date": "2025-11-06",
      "time": "21:30",
      "location": "SACILE",
      "opponent": "SACILE CALCIO A 5",
      "result": "4-3",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec3zj3tSnO0IzOqF",
      "type": "match",
      "title": "TC Caneva vs BOMBA C5",
      "date": "2025-10-24",
      "time": "20:30",
      "location": "VALERY SPACE",
      "opponent": "BOMBA C5",
      "result": "2-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec4oEgIcH3vivdga",
      "type": "match",
      "title": "TC Caneva vs LIBERTAS C5",
      "date": "2025-12-04",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "LIBERTAS C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recAL7oAGLqyvgyx4",
      "type": "match",
      "title": "TC Caneva vs FCS",
      "date": "2025-10-30",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "FCS",
      "result": "4-7",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recBmIO9wCikSA01D",
      "type": "match",
      "title": "TC Caneva vs ATLETICO CONEGLIANO C5",
      "date": "2025-11-18",
      "time": "21:30",
      "location": "CONEGLIANO",
      "opponent": "ATLETICO CONEGLIANO C5",
      "result": "3-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recDAzLnpPRLzPnKl",
      "type": "match",
      "title": "TC Caneva vs BOWMAN PUB C5",
      "date": "2025-12-12",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "BOWMAN PUB C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recDMiOZV98zKfKaT",
      "type": "match",
      "title": "TC Caneva vs BCC PORDENONESE E MONSILE",
      "date": "2026-01-23",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "BCC PORDENONESE E MONSILE",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recEMUk5PaeoIQzC6",
      "type": "match",
      "title": "TC Caneva vs PIZZERIA AMICI MIEI C5",
      "date": "2025-10-16",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "PIZZERIA AMICI MIEI C5",
      "result": "1-3",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recEaGnxMoz0hbM4Z",
      "type": "match",
      "title": "TC Caneva vs PIZZERIA DA MARIO",
      "date": "2025-11-03",
      "time": "20:30",
      "location": "FANNA",
      "opponent": "PIZZERIA DA MARIO",
      "result": "9-1",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recFikcX4135keURD",
      "type": "match",
      "title": "TC Caneva vs BLACKMAGIC",
      "date": "2026-01-22",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "BLACKMAGIC",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recHK7tbomPmaVVyG",
      "type": "match",
      "title": "TC Caneva vs ATLETICO MARENO C5",
      "date": "2025-11-14",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "ATLETICO MARENO C5",
      "result": "5-1",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recQNnsIvhcZTojfa",
      "type": "match",
      "title": "TC Caneva vs PIGOZZI TEAM",
      "date": "2025-10-16",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "PIGOZZI TEAM",
      "result": "5-5",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recQzHSlVra1JU4yP",
      "type": "match",
      "title": "TC Caneva vs FUTSAL OLME' 2012",
      "date": "2025-11-20",
      "time": "20:30",
      "location": "CESSALTO",
      "opponent": "FUTSAL OLME' 2012",
      "result": "4-9",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recUZvKUVy4DmTI3Y",
      "type": "match",
      "title": "TC Caneva vs A.S.D. ORIGINALS 2022",
      "date": "2025-10-24",
      "time": "21:30",
      "location": "S.PIETRO DI FELETTO",
      "opponent": "A.S.D. ORIGINALS 2022",
      "result": "3-3",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recV1a6vmvQwPjh4M",
      "type": "match",
      "title": "TC Caneva vs CAVOLANO UNITED",
      "date": "2025-11-13",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "CAVOLANO UNITED",
      "result": "1-3",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recW731hixsbngLyb",
      "type": "match",
      "title": "TC Caneva vs SCAFATI FUTSAL",
      "date": "2025-11-24",
      "time": "21:30",
      "location": "CORDENONS",
      "opponent": "SCAFATI FUTSAL",
      "result": "9-2",
      "homeAway": "",
      "round": ""
    },
    {
      "id": "recXNhEW5zHMDFdXE",
      "type": "match",
      "title": "TC Caneva vs SAN GIORGIO",
      "date": "2025-10-20",
      "time": "20:30",
      "location": "VALERY SPACE",
      "opponent": "SAN GIORGIO",
      "result": "3-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recYvei6zTqkUjonx",
      "type": "match",
      "title": "TC Caneva vs FUTSAL OLME' 2012",
      "date": "2025-11-27",
      "time": "20:30",
      "location": "CESSALTO",
      "opponent": "FUTSAL OLME' 2012",
      "result": "4-8",
      "homeAway": "trasferta",
      "round": ""
    },
    {
      "id": "recg5pAiv7sRSEXrv",
      "type": "match",
      "title": "TC Caneva vs CALCIO A 5 ANZANO",
      "date": "2025-11-28",
      "time": "20:30",
      "location": "FREGONA (TV)",
      "opponent": "CALCIO A 5 ANZANO",
      "result": "2-5",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rechUan3g8uBwLaL2",
      "type": "match",
      "title": "TC Caneva vs FC REAL CELTIC",
      "date": "2026-01-09",
      "time": "20:10",
      "location": "ZOPPOLA",
      "opponent": "FC REAL CELTIC",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recifWHt5FmmKWgg8",
      "type": "match",
      "title": "TC Caneva vs CAFFE' CARIOCA",
      "date": "2025-12-15",
      "time": "20:45",
      "location": "PASIANO",
      "opponent": "CAFFE' CARIOCA",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recjfk8IygZGq7TcH",
      "type": "match",
      "title": "TC Caneva vs PORDENONE NAONIS FUTSAL",
      "date": "2025-10-17",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "PORDENONE NAONIS FUTSAL",
      "result": "6-1",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recmmoOg2QmXQXlve",
      "type": "match",
      "title": "TC Caneva vs NORMANNI",
      "date": "2025-11-13",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "NORMANNI",
      "result": "1-5",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "reco0LuLWHzlV2t3j",
      "type": "match",
      "title": "TC Caneva vs GREENFUTSAL",
      "date": "2025-12-11",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "GREENFUTSAL",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recoKVFtdCi0xJTGO",
      "type": "match",
      "title": "TC Caneva vs ASD ICEM C5",
      "date": "2025-11-28",
      "time": "20:15",
      "location": "VALERY SPACE",
      "opponent": "ASD ICEM C5",
      "result": "6-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recrUR9kIAOq6pl5N",
      "type": "match",
      "title": "TC Caneva vs ASD ICEM C5",
      "date": "2025-12-05",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "ASD ICEM C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recsEEZLpPzDAzrel",
      "type": "match",
      "title": "TC Caneva vs FASAN MOTORS C5",
      "date": "2025-12-11",
      "time": "22:25",
      "location": "ORSAGO",
      "opponent": "FASAN MOTORS C5",
      "result": "",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "rectACT7lXDleEGL5",
      "type": "match",
      "title": "TC Caneva vs I FANTAS",
      "date": "2025-10-31",
      "time": "20:00",
      "location": "ORSAGO",
      "opponent": "I FANTAS",
      "result": "4-4",
      "homeAway": "casa",
      "round": "andata"
    },
    {
      "id": "recw6MXBm1KG1CFXo",
      "type": "match",
      "title": "TC Caneva vs STELLA D'ARGENTO",
      "date": "2025-12-15",
      "time": "22:00",
      "location": "PASIANO",
      "opponent": "STELLA D'ARGENTO",
      "result": "",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "recwVkNFEN8JyQhBQ",
      "type": "match",
      "title": "TC Caneva vs PONTE 94",
      "date": "2025-11-17",
      "time": "21:15",
      "location": "FIASCHETTI",
      "opponent": "PONTE 94",
      "result": "1-7",
      "homeAway": "casa",
      "round": ""
    },
    {
      "id": "recxvu5EEXgqAsFDG",
      "type": "match",
      "title": "TC Caneva vs CENTRO EDIL LEGNO",
      "date": "2025-11-28",
      "time": "21:15",
      "location": "ORSAGO",
      "opponent": "CENTRO EDIL LEGNO",
      "result": "7-2",
      "homeAway": "trasferta",
      "round": "andata"
    },
    {
      "id": "rec3ocuazTMO1Ndx3",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec4GUj2OZsgFZRb1",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec5mDhvUpUtpnKDy",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec5uAjK1Ds6p1wA3",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec7b7Xx5h0BqvLgp",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rec9lSTh5sHGMApjU",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "recNQDKG7cbtXjzKN",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "recXREj36QwTNvz7y",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "reccUOX2btwLUxTaf",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rech9lmvj9m7ggbbK",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    },
    {
      "id": "rechG4sFM0NarecXh",
      "type": "training",
      "title": "Allenamento",
      "date": "",
      "time": "",
      "location": ""
    }
  ]
}
